### ISSUE TITLE
Are these lists active?

### ISSUE THREAD

**Issue by iSaluki** [safing/intel-data#24]
After doing a bit of digging I can't tell if these lists are currently used by Portmaster, as PM seems to be blocking some domains that aren't on these lists. I just wanted to confirm this before looking into contributing any new domains.

**Comment by iSaluki** [comment]
Found sources.yml, which explains my issue. Sorry for bothering you.

**Comment by dhaavi** [comment]
> sources.yml

Yup, that's it.

You can also view all lists in their hierarchy in the Portmaster settings by opening the sections. This might be quite a bit easier for going through them.
