### ISSUE TITLE
[Suggestion] PhishTank and OpenPhish

### ISSUE THREAD

**Issue by curbengh** [safing/intel-data#25]
- [PhishTank](https://www.phishtank.com/), operated and used by Cisco.
- [OpenPhish](https://openphish.com/)

**Comment by dhaavi** [comment]
Hey @curbengh, thanks for the great suggestions.

We already have these on our radar, but their integration is more difficult, as they are URL-based.
This means we have to parse the lists and decide which entries to use, and which of them not.

But we definitely want to do it.
