### ISSUE TITLE
New AdList [Estonian]

### ISSUE THREAD

**Issue by TrueBeastEmperor** [safing/intel-data#49]
site: https://adblock.ee/
list: https://adblock.ee/list.php
Author: Unknown
Language: Estonian
Encoding: UTF-8

Place where list taken:
https://adblockultimate.net/filters

**Comment by dhaavi** [comment]
Hey @TrueBeastEmperor, 

Unfortunately Portmaster works on the network level and cannot see URLs. That means we cannot apply adblock rules.
