### ISSUE TITLE
[Suggestion] On GitHub please add the following and/or similar case example on how to create and issue or suggestin

### ISSUE THREAD

**Issue by TrueBeastEmperor** [safing/intel-data#55]
## Title:
*In your title add the applicable tags in the following format [Suggestion]; [Idea];[Desktop (System type – Windows; Mac; Linux)]; [Mobile (Android; iOS; Huawei; Other)]*

## Description of problem:
*Describe your problem with as many details as possible*

## Steps to reproduce:
*What and how do you believe you might have triggered the error. For example: Laptop restart; another application open, etc.*

## Any images:
*Insert any images here that you believe will help in reproducing the problem and/or help in describing your problem*

## Debug file:
*Go to Portmaster app, open the screwdriver&wench “🛠”  symbol, on the bottom click “Copy debug info” and paste that into any Notepad app you have. Save the file as a text (.txt) file.*

**Comment by dhaavi** [comment]
Hey @TrueBeastEmperor, thanks for the suggestion.

We will add a template if more issues are created in this repo.
For now, I think everything seems to work well.
