### ISSUE TITLE
New Google domains (confirmed by, Next DNS)

### ISSUE THREAD

**Issue by ghost** [safing/intel-data#69]
These domains should be added to the Google block list.  They are identified as Google domains by Next DNS.

app-measurement.com
pki.goog
googleusercontent.com

**Comment by Linux-Is-Best** [comment]
You may also want to add:  gvt3.com

**Comment by Linux-Is-Best** [comment]
You can also add: googlesyndication.com

**Comment by Raphty** [comment]
thank you for listing them here, please consider doing so in a PR
