### ISSUE TITLE
Please add  1e100.net to Google list 

### ISSUE THREAD

**Issue by ghost** [safing/intel-data#72]
A lot of tracking from Google seems to pass through that.  Confirmed it is owned by Google too.

https://www.whois.com/whois/1e100.net

**Comment by Raphty** [comment]
what filter lists did you have active?

**Comment by Linux-Is-Best** [comment]
> what filter lists did you have active?

As the title said, please add this to your GOOGLE list.

Pr? Push release?  I am sorry, it would be better if this was on GitLab.  I am de-Googling and de-Microsofting, which means this account will soon be deleted.

**Comment by eabase** [comment]
@Raphty 

Completed where? 

This is a nasty data and PII collection domain, hiding under googles umbrella.
